export enum RejectionType {
  INVALID_AMOUNT = "INVALID_AMOUNT",
  MISSING_PARTY = "MISSING_PARTY",
  DUPLICATE_EVENT = "DUPLICATE_EVENT",
  INVALID_SCHEMA = "INVALID_SCHEMA",
  POLICY_VIOLATION = "POLICY_VIOLATION",
}
